import React from 'react';
import Content from '../../shared/Content';

const JustDaoIt = () => {
  return (
    <Content>
      <div>
        <p>
          Being part of a DAO is exciting and shows faith in collective
          intelligence. This is how the DAO works:
        </p>
        <ul>
          <li>Cryptorontonians govern Cryptorontonians DAO</li>
          <li>Owning a Cryptorontonian grants you access to the DAO.</li>
          <li>Cryptorontonians can vote on proposals.</li>
          <li>One Cryptorontonian = One vote.</li>
          <li>
            Cryptorontonians can submit proposals - A minimum ownership of 3
            Cryptorontonians is required.
          </li>
        </ul>
        <div className="font-bold text-lg">
          On-chain Cash Flow
        </div>
        <p>
          The DAO automatically receives 25% of all the profits generated by Non
          Fungible Thrills through the sale of Cryptorontonians and all its
          future projects, including royalties on secondary sales.
        </p>
        <p>
          DAO members can submit proposals on how to manage and grow the DAO
          treasury. These proposals can include investments in ventures such as
          purchasing other NFTs, investing in crypto, growing the
          Cryptorontonians IP, events, donating to charities…the possibilities
          are endless and are up to the DAO members! All DAO members can vote on
          these proposals.
        </p>
        <p>
          Special Veto: Governance is currently in a soft-launch phase to ensure
          that no malicious proposals can be passed while the Cryptorontonians
          demand is low.
        </p>
      </div>
    </Content>
  );
};

export default JustDaoIt;
