import React from 'react';
import Content from '../../shared/Content';
import NextImage from '../../shared/NextImage';

const TheVirtuousCycle = () => {
  return (
    <Content>
      <p>
        Cryptorontonians are dope and designed in a way to bring massive
        long-term value to the holders. Take a look at this:
      </p>
      <NextImage src="/virtuous_cycle.jpeg" width={1024} height={1034} />
      <p>
        In other words, 25% of the profits generated by the sale of
        Cryptorontonians are automatically funnelled to the Cryptorontonians
        DAO. The remaining 75% of the profits are invested in developing new
        projects. New projects donate 25% of their profits to the
        Cryptorontonians DAO.
      </p>
      <p>
        It’s a virtuous cycle! The better the new projects do, the more the DAO
        treasury grows; the more the DAO treasury grows, the more valuable the
        Cryptorontonians become; the more valuable the Cryptorontonians are, the
        more Non Fungible Thrills grows; and, the more Non Fungible Thrills
        grows, the more dope projects we can create… you get the idea!
      </p>
    </Content>
  );
};

export default TheVirtuousCycle;
