import React from 'react';
import { Layout } from '../components/Layout';

const TermsAndConditions = () => {
  return (
    <Layout isPresale>
      <div className="max-w-5xl mx-auto mt-8 px-4 lg:px-0">
        <div className="prose lg:prose-lg">
          <h2 className="font-bebasNeue">TERMS & CONDITIONS</h2>
          <p>
            Cryptorontonians is a collection of digital artworks (NFTs) running
            on the Ethereum network. This website is only an interface allowing
            participants to exchange digital collectibles. Users are entirely
            responsible for the safety and management of their own private
            Ethereum wallets and validating all transactions and contracts
            generated by this website before approval. Furthermore, as the
            Cryptorontonians smart contract runs on the Ethereum network, there
            is no ability to undo, reverse, or restore any transactions.
          </p>
          <p>
            This website and its connected services are provided “as is” and “as
            available” without warranty of any kind. By using this website you
            are accepting sole responsibility for any and all transactions
            involving Cryptorontonians digital collectibles.
          </p>
          <span className="text-xl font-medium text-black">OWNERSHIP</span>
          <p>
            i. You Own the NFT. Each Cryptorontonian is an NFT on the Ethereum
            blockchain. When you purchase an NFT, you own the underlying
            Cryptorontonian, the Art, completely. Ownership of the NFT is
            mediated entirely by the Smart Contract and the Ethereum Network: at
            no point may we seize, freeze, or otherwise modify the ownership of
            any Cryptorontonian.
          </p>
          <p>
            ii. Personal Use. Subject to your continued compliance with these
            Terms, Non Fungible Thrills grants you a worldwide, royalty-free
            license to use, copy, and display the purchased Art, along with any
            extensions that you choose to create or use, solely for the
            following purposes: (i) for your own personal, non-commercial use;
            (ii) as part of a marketplace that permits the purchase and sale of
            your Cryptorontonian / NFT, provided that the marketplace
            cryptographically verifies each Cryptorontonian owner’s rights to
            display the Art for their Cryptorontonian to ensure that only the
            actual owner can display the Art; or (iii) as part of a third party
            website or application that permits the inclusion, involvement, or
            participation of your Cryptorontonians, provided that the
            website/application cryptographically verifies each Cryptorontonian
            owner’s rights to display the Art for their Cryptorontonian to
            ensure that only the actual owner can display the Art, and provided
            that the Art is no longer visible once the owner of the
            Cryptorontonian leaves the website/application.
          </p>
          <p>
            iii. Commercial Use. Subject to your continued compliance with these
            Terms, Non Fungible Thrills grants you an unlimited, worldwide
            license to use, copy, and display the purchased Art for the purpose
            of creating derivative works based upon the Art (“Commercial Use”).
            Examples of such Commercial Use would e.g. be the use of the Art to
            produce and sell merchandise products (T-Shirts etc.) displaying
            copies of the Art. For the sake of clarity, nothing in this Section
            will be deemed to restrict you from (i) owning or operating a
            marketplace that permits the use and sale of Cryptorontonians
            generally, provided that the marketplace cryptographically verifies
            each Cryptorontonian owner’s rights to display the Art for their
            Cryptorontonian to ensure that only the actual owner can display the
            Art; (ii) owning or operating a third party website or application
            that permits the inclusion, involvement, or participation of
            Cryptorontonians generally, provided that the third party website or
            application cryptographically verifies each Cryptorontonian owner’s
            rights to display the Art for their Cryptorontonian to ensure that
            only the actual owner can display the Art, and provided that the Art
            is no longer visible once the owner of the Purchased Cryptorontonian
            leaves the website/application; or (iii) earning revenue from any of
            the foregoing.
          </p>
          <p />
          <br />
        </div>
      </div>
    </Layout>
  );
};

export default TermsAndConditions;
